title: Marc O'Morain
email: www@marcomorain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal site..
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.marcomorain" # the base hostname & protocol for your site
twitter_username: atmarc
github_username:  marcomorain
linkedin_username: marcomorain

# Build settings
markdown: kramdown
